name: Deploy Sentinel Rules

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy Sentinel Rules
        uses: Azure/cli@v1
        with:
          inlineScript: |
            for file in ./sentinel-rules/*.json; do
              az sentinel alert-rule create \
                --resource-group soc \
                --workspace-name soc-law \
                --name "$(basename "$file" .json)" \
                --rule "$(cat "$file")"
            done
